import { EventEmitter } from 'events';
import { Dots, Mouse, RectRenderQueue, Stroke, Text, TooltipField } from '../types';
import { OffscreenRenderEngine } from './offscreen-render-engine';
import { RenderEngine } from './render-engine';
export declare type RenderOptions = {
    tooltip?: ((data: any, renderEngine: RenderEngine | OffscreenRenderEngine, mouse: Mouse | null) => boolean | void) | boolean;
    timeUnits: string;
};
export declare type RenderStyles = {
    blockHeight: number;
    blockPaddingLeftRight: number;
    backgroundColor: string;
    font: string;
    fontColor: string;
    tooltipHeaderFontColor: string;
    tooltipBodyFontColor: string;
    tooltipBackgroundColor: string;
    headerHeight: number;
    headerColor: string;
    headerStrokeColor: string;
    headerTitleLeftPadding: number;
};
export declare type RenderSettings = {
    options?: Partial<RenderOptions>;
    styles?: Partial<RenderStyles>;
};
export declare const defaultRenderSettings: RenderOptions;
export declare const defaultRenderStyles: RenderStyles;
export declare class BasicRenderEngine extends EventEmitter {
    width: number;
    height: number;
    isSafari: boolean;
    canvas: HTMLCanvasElement;
    ctx: CanvasRenderingContext2D;
    pixelRatio: number;
    options: RenderOptions;
    timeUnits: any;
    styles: RenderStyles;
    blockPaddingLeftRight: number;
    blockHeight: number;
    blockPaddingTopBottom: number;
    charHeight: number;
    placeholderWidth: number;
    avgCharWidth: number;
    minTextWidth: number;
    textRenderQueue: Text[];
    strokeRenderQueue: Stroke[];
    rectRenderQueue: RectRenderQueue;
    lastUsedColor: string | null;
    lastUsedStrokeColor: string | null;
    zoom: number;
    positionX: number;
    min: number;
    max: number;
    constructor(canvas: HTMLCanvasElement, settings: RenderSettings);
    setSettings({ options, styles }: RenderSettings): void;
    reset(): void;
    setCtxColor(color: string): void;
    setStrokeColor(color: string): void;
    setCtxFont(font: string): void;
    fillRect(x: number, y: number, w: number, h: number): void;
    fillText(text: string, x: number, y: any): void;
    renderBlock(color: string, x: number, y: number, w: number): void;
    renderStroke(color: string, x: number, y: number, w: number, h: number): void;
    clear(w?: number, h?: number, x?: number, y?: number): void;
    timeToPosition(time: number): number;
    pixelToTime(width: number): number;
    setZoom(zoom: number): void;
    setPositionX(x: number): number;
    addRectToRenderQueue(color: string, x: number, y: number, w: number): void;
    addTextToRenderQueue(text: string, x: number, y: number, w: number): void;
    addStrokeToRenderQueue(color: string, x: number, y: number, w: number, h: number): void;
    resolveRectRenderQueue(): void;
    resolveTextRenderQueue(): void;
    resolveStrokeRenderQueue(): void;
    setMinMax(min: number, max: number): void;
    getTimeUnits(): any;
    tryToChangePosition(positionDelta: number): void;
    getInitialZoom(): number;
    getRealView(): number;
    resetView(): void;
    resize(width?: number, height?: number): boolean;
    applyCanvasSize(): void;
    copy(engine: OffscreenRenderEngine): void;
    renderTooltipFromData(fields: TooltipField[], mouse: Mouse): void;
    renderShape(color: string, dots: Dots, posX: number, posY: number): void;
    renderTriangle(color: string, x: number, y: number, width: number, height: number, direction: 'bottom' | 'left' | 'right' | 'top'): void;
    renderCircle(color: string, x: number, y: number, radius: number): void;
}
//# sourceMappingURL=basic-render-engine.d.ts.map